name: Backend Lint and Test

on:
  push:
    branches:
      - main
    paths:
      - backend/**

env:
  DATABASE_TYPE: postgresql
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  DATABASE_NAME: todo_db
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres

jobs:
  lint-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15.4
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          PGSSLMODE: disable
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          uv-version: 0.6.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "backend/.python-version"

      - name: Install the project
        run: cd backend && uv sync --all-extras --dev

      - name: Ruff Check
        run: cd backend && uv run ruff check --output-format=github .

      - name: Run Tests
        run: cd backend && uv run pytest


